package sessionhost

import (
	"bufio"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"sync"
	"syscall"
	"time"
)

// Client is the Daemon-side control client for one Session Host. A client is
// deliberately stateless between calls; reconnecting after a Daemon restart
// only requires loading metadata and the token again.
type Client struct {
	mu       sync.RWMutex
	metadata Metadata
	token    string
}

func NewClient(metadataPath string) (*Client, error) {
	metadata, err := LoadMetadata(metadataPath)
	if err != nil {
		return nil, err
	}
	tokenBody, err := os.ReadFile(metadata.TokenFile)
	if err != nil {
		return nil, fmt.Errorf("read session-host token: %w", err)
	}
	return &Client{metadata: metadata, token: string(trimSpaceBytes(tokenBody))}, nil
}

func (c *Client) Metadata() Metadata {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.metadata
}
func (c *Client) AttachSocket() string { return c.Metadata().AttachSocket }

// Call sends one authenticated request and waits for its response. The Host
// protocol is request/response per connection, so a lost Daemon connection
// cannot leave a half-open controller stream in the Host.
func (c *Client) Call(ctx context.Context, typ string, payload any, result any) error {
	if c == nil {
		return errors.New("session-host client is not initialized")
	}
	c.mu.RLock()
	controlSocket, token := c.metadata.ControlSocket, c.token
	c.mu.RUnlock()
	if controlSocket == "" || token == "" {
		return errors.New("session-host client is not initialized")
	}
	conn, err := (&netDialer{}).dial(ctx, controlSocket)
	if err != nil {
		return err
	}
	defer conn.Close()
	body, err := json.Marshal(payload)
	if err != nil {
		return err
	}
	req := request{Version: MetadataVersion, RequestID: newRequestID(), Token: token, Type: typ, Payload: body}
	if err := json.NewEncoder(conn).Encode(req); err != nil {
		return err
	}
	var reply response
	if err := json.NewDecoder(bufio.NewReader(conn)).Decode(&reply); err != nil {
		return err
	}
	if !reply.OK {
		if reply.Error == "" {
			reply.Error = "session-host request failed"
		}
		return errors.New(reply.Error)
	}
	if result != nil && reply.Payload != nil {
		encoded, err := json.Marshal(reply.Payload)
		if err != nil {
			return err
		}
		return json.Unmarshal(encoded, result)
	}
	return nil
}

func (c *Client) State(ctx context.Context) (Metadata, error) {
	var payload statePayload
	if err := c.Call(ctx, "state", nil, &payload); err != nil {
		return Metadata{}, err
	}
	c.mu.Lock()
	c.metadata = payload.Metadata
	metadata := c.metadata
	c.mu.Unlock()
	return metadata, nil
}

func (c *Client) Input(ctx context.Context, content string) error {
	return c.Call(ctx, "input", map[string]string{"content": content}, nil)
}

func (c *Client) Stop(ctx context.Context) error { return c.Call(ctx, "stop", nil, nil) }
func (c *Client) Ping(ctx context.Context) error { return c.Call(ctx, "ping", nil, nil) }

// Subscribe keeps one authenticated control connection open and receives
// input events generated by either an attach client or a control request. The
// callback is intentionally the only data extracted; raw terminal bytes never
// leave the Host through this event stream.
func (c *Client) Subscribe(ctx context.Context, onInput func(string)) error {
	if c == nil {
		return errors.New("session-host client is not initialized")
	}
	c.mu.RLock()
	controlSocket, token := c.metadata.ControlSocket, c.token
	c.mu.RUnlock()
	if controlSocket == "" || token == "" {
		return errors.New("session-host client is not initialized")
	}
	conn, err := (&netDialer{}).dial(ctx, controlSocket)
	if err != nil {
		return err
	}
	defer conn.Close()
	cancel := make(chan struct{})
	defer close(cancel)
	go func() {
		select {
		case <-ctx.Done():
			_ = conn.Close()
		case <-cancel:
		}
	}()
	if err := json.NewEncoder(conn).Encode(request{Version: MetadataVersion, RequestID: newRequestID(), Token: token, Type: "subscribe"}); err != nil {
		return err
	}
	decoder := json.NewDecoder(bufio.NewReader(conn))
	var reply response
	if err := decoder.Decode(&reply); err != nil {
		return err
	}
	if !reply.OK {
		return errors.New(reply.Error)
	}
	for {
		if err := decoder.Decode(&reply); err != nil {
			return err
		}
		if reply.Type != "input" || onInput == nil {
			continue
		}
		body, err := json.Marshal(reply.Payload)
		if err != nil {
			continue
		}
		var payload struct {
			Content string `json:"content"`
		}
		if json.Unmarshal(body, &payload) == nil && payload.Content != "" {
			onInput(payload.Content)
		}
	}
}

func (c *Client) Rebind(ctx context.Context, sessionID, agentSessionID, historyPath, displayName string) (Metadata, error) {
	var payload statePayload
	err := c.Call(ctx, "rebind", rebindPayload{SessionID: sessionID, AgentSessionID: agentSessionID, HistoryPath: historyPath, DisplayName: displayName}, &payload)
	if err != nil {
		return Metadata{}, err
	}
	c.mu.Lock()
	c.metadata = payload.Metadata
	metadata := c.metadata
	c.mu.Unlock()
	return metadata, nil
}

// Spawn starts a detached session-host process and waits for its metadata and
// control socket. executable should be the Agora binary. The returned Client
// is immediately usable by the Daemon and remains usable after the spawning
// Daemon exits.
func Spawn(ctx context.Context, executable string, config Config) (*Client, error) {
	return SpawnWithEnv(ctx, executable, config, nil)
}

// SpawnWithEnv passes the provider environment directly to the Host process
// without serializing it into launch.json. Environment variables can contain
// credentials and must not be persisted in the runtime metadata.
func SpawnWithEnv(ctx context.Context, executable string, config Config, env []string) (*Client, error) {
	if executable == "" {
		return nil, errors.New("session-host executable is required")
	}
	if config.HostID == "" {
		config.HostID = newID()
	}
	if config.RuntimeDir == "" {
		home, _ := os.UserHomeDir()
		config.RuntimeDir = filepath.Join(home, ".agora", "runtime", "sessions", config.HostID)
	}
	if err := os.MkdirAll(config.RuntimeDir, 0o700); err != nil {
		return nil, err
	}
	configPath := filepath.Join(config.RuntimeDir, "launch.json")
	config.Env = nil
	body, err := json.Marshal(config)
	if err != nil {
		return nil, err
	}
	if err := writePrivateFile(configPath, append(body, '\n')); err != nil {
		return nil, err
	}
	cmd := exec.Command(executable, "session-host", "--config", configPath)
	if env != nil {
		cmd.Env = env
	}
	// The Host owns the Agent, so it must not share the Daemon's session or
	// process group. Otherwise a Ctrl-C in the terminal that started the Daemon
	// (or a SIGHUP when that terminal closes) is delivered to the whole
	// foreground process group, kills the Host, and the Agent then exits because
	// its PTY master closed. Daemon.Close never signals this child; the Host is
	// orphaned and adopted by the system when the Daemon exits.
	cmd.SysProcAttr = &syscall.SysProcAttr{Setsid: true}
	if err := cmd.Start(); err != nil {
		_ = os.RemoveAll(config.RuntimeDir)
		return nil, fmt.Errorf("start session-host: %w", err)
	}
	// Reap the session-host process itself while allowing it to outlive the
	// Daemon. This Wait is for the Host child; the Host separately waits for
	// the Agent child it owns, so the two waits do not race.
	hostDone := make(chan error, 1)
	go func() { hostDone <- cmd.Wait() }()
	metadataPath := filepath.Join(config.RuntimeDir, "metadata.json")
	deadline := time.Now().Add(10 * time.Second)
	for time.Now().Before(deadline) {
		select {
		case hostErr := <-hostDone:
			return nil, fmt.Errorf("session-host exited before becoming ready: %w", hostErr)
		default:
		}
		if _, loadErr := LoadMetadata(metadataPath); loadErr == nil {
			client, clientErr := NewClient(metadataPath)
			if clientErr == nil {
				if _, stateErr := client.State(ctx); stateErr == nil {
					return client, nil
				}
			}
		}
		select {
		case <-ctx.Done():
			_ = cmd.Process.Signal(syscall.SIGTERM)
			return nil, ctx.Err()
		case <-time.After(50 * time.Millisecond):
		}
	}
	_ = cmd.Process.Signal(syscall.SIGTERM)
	select {
	case <-hostDone:
	case <-time.After(time.Second):
	}
	return nil, fmt.Errorf("session-host did not become ready")
}

type netConn interface {
	Close() error
	Read([]byte) (int, error)
	Write([]byte) (int, error)
}

type netDialer struct{}

func (*netDialer) dial(ctx context.Context, path string) (netConn, error) {
	var dialer net.Dialer
	return dialer.DialContext(ctx, "unix", path)
}

func trimSpaceBytes(value []byte) []byte {
	start, end := 0, len(value)
	for start < end && (value[start] == ' ' || value[start] == '\t' || value[start] == '\r' || value[start] == '\n') {
		start++
	}
	for end > start && (value[end-1] == ' ' || value[end-1] == '\t' || value[end-1] == '\r' || value[end-1] == '\n') {
		end--
	}
	return value[start:end]
}

func newRequestID() string { return fmt.Sprintf("req-%d", time.Now().UnixNano()) }

func writePrivateFile(path string, body []byte) error {
	if err := os.WriteFile(path, body, 0o600); err != nil {
		return err
	}
	return os.Chmod(path, 0o600)
}
