export type Coordination = { id: string; name: string; created_at: string };
export type Capabilities = {
  can_start: boolean;
  can_discover: boolean;
  can_attach: boolean;
  can_observe: boolean;
  can_send_input: boolean;
  can_stream: boolean;
  can_interrupt: boolean;
  can_resume: boolean;
  can_approve: boolean;
  can_read_history: boolean;
  can_read_terminal: boolean;
};
export type Session = {
  id: string;
  coordination_id: string;
  daemon_id?: string;
  agent: string;
  agent_session_id?: string;
  /** @deprecated use agent_session_id */
  claude_session_id?: string;
  workspace: string;
  display_name: string;
  display_name_source?: "initial" | "custom" | "first_user" | "ai_title";
  role: string;
  state: string;
  source: string;
  connection?: string;
  process_id?: number;
  history_path?: string;
  last_error?: string;
  capabilities: Capabilities;
  created_at: string;
  updated_at: string;
};
export type Device = {
  device_id: string;
  name: string;
  connected: boolean;
  created_at: string;
  last_seen_at?: string;
  revoked_at?: string;
};
export type Event = {
  id: string;
  external_id?: string;
  session_id: string;
  source?: string;
  kind: string;
  type?: string;
  role?: string;
  subtype?: string;
  content: string;
  summary?: string;
  tool_name?: string;
  tool_input?: string;
  tool_output?: string;
  thinking?: string;
  is_error?: boolean;
  raw_json?: string;
  created_at: string;
};
export type PTYSnapshot = {
  sequence: number;
  captured_at: string;
  cols: number;
  rows: number;
  lines: string[];
  cursor_col: number;
  cursor_row: number;
  cursor_visible: boolean;
  alternate_screen: boolean;
  healthy: boolean;
};
export type Message = {
  id: string;
  coordination_id: string;
  sender: { type: string; id: string };
  recipient: { type: string; id: string };
  content: string;
  status: string;
  error?: string;
  created_at: string;
};
